### ISSUE TITLE
SIC and SIC Notícias streams are not working.

### ISSUE THREAD

**Issue by marmelo** [marmelo/streaming-pt#15]
Actually, there is no official stream mentioned in their website.
But sometimes `videos.sapo.pt`  has live broadcasts from these channels and we may try to catch the streams.

**Comment by marado** [comment]
I'm guessing that "partially fixes" automaticly closed this issue, but you want it open, still?

**Comment by marmelo** [comment]
I'll just keep this one closed and open another only for SIC stream.
Thanks for the heads up!
