### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by SpyderSC** [marmelo/streaming-pt#33]
The links **TVI** and **TVI24** are broken! Can you fix this?

**Comment by marmelo** [comment]
Hi @SpyderSC, I have just updated both TVI and TVI24 streams.
I am having some issues with TVI after about 10s of streaming but TVI24 is working 100%.
I am having the same error with TVI through the browser, so lets hope that they fix the issue.

I am happy to fix the streams when they break, but feel free to fix them yourself and send me a pull request. :)

Let me know if you have any issues.
