### ISSUE TITLE
Canais RTP off

### ISSUE THREAD

**Issue by LITUATUI** [marmelo/streaming-pt#53]
Parece que os canais da RTP agora requerem um token para funcionar, tal como os da TVI.

**Comment by marmelo** [comment]
@LITUATUI obrigado pela informação.

Obter o token através da página web é a forma mais simples.
Parece que o token obtido tem a validade de alguns dias.

Estive a analisar o APK da app RTP Play e existe um mecanismo para obter o token programaticamente.
No entanto, é necessário colocar um header obtido com base em hashes criptográficas (HmacSHA256) e isso não é muito simples de fazer em bash sem adicionar mais dependências.
