### ISSUE TITLE
Give colaborative access to streaming-pt repo.

### ISSUE THREAD

**Issue by marmelo** [marmelo/streaming-pt#59]
Hi @marado @A1ve5 @fimdomeio @LITUATUI @manuelvsousa @defer @dnegreira,

What do you think if I add you (if you want) as repo contributers and setup a pull request policy?
Something like no commits to master, pull request approval of ~half of contributters.
This way this repo becomes truly colaborative and may continue to evolve without me being a single point of failure.

Let me know what you think.

**Comment by marado** [comment]
I'm OK with it.

**Comment by marmelo** [comment]
I've just added @marado @LITUATUI and @A1ve5 as collaborators.
Each pull request requires 2 approving reviews to be merged into master.
We can review if this is too limitative.
