### ISSUE TITLE
TVI and TVI24 streams are not working.

### ISSUE THREAD

**Issue by marmelo** [marmelo/streaming-pt#6]

**Comment by marado** [comment]
They're working for me...

**Comment by marmelo** [comment]
Not an issue.

**Comment by LITUATUI** [comment]
TVI dynamic streams aren't working.

**Comment by marmelo** [comment]
Hi @LITUATUI, @marado :star: has just fixed the streams. 

Thanks for raising the issue!
But next time please create a new issue instead of commenting in an old one.
