### ISSUE TITLE
RTP 1 is off

### ISSUE THREAD

**Issue by LITUATUI** [marmelo/streaming-pt#61]
It seems that AES encryption is now being used.

**Comment by GDLMendonca** [comment]
Experiencing the same on my end.
FFMPEG doesn't know how to handle AES it seems...

**Comment by eSoares** [comment]
Widevine (DRM) is being used.

**Comment by ner00** [comment]
I suppose we can forget streaming the content freely and easily then. I don't know anything about the scheme beside what I've read for the past 30 minutes, but it all seems to point that this could be using the least secure level of Widevine, but even then it's still quite the hurdle where you need to recover the encryption keys for the stream before being able to output an unencrypted stream.

VLC, MPC and other players of the sort are too stiff to implement this, although a plugin would be feasible with the right people. So far I've slightly read about Kodi using `inputstream.adaptive` although I'm not entirely sure how the workflow goes; another option would be Google's own Shaka Player, in a similar fashion. In any case, this would need to be customized for specific streams/channels. I' not familiar with any approach though, just keeping the discussion open.

**Comment by marado** [comment]
It is working again: no more DRM on either RTP1 or RTP2.
