### ISSUE TITLE
Portugal news isnt working

### ISSUE THREAD

**Issue by spotanjo3** [marmelo/streaming-pt#68]
Sic Noticias

**Comment by marado** [comment]
Confirming that is is still working (with a Portuguese IP).

**Comment by spotanjo3** [comment]
> SIC Notícias only works with Portuguese IP.
> 
> If you don't live in Portugal you'll have to use a VPN.

Geo-blocked, huh?

**Comment by LITUATUI** [comment]
> 

Correct.
