### ISSUE TITLE
Euronews stream is not working.

### ISSUE THREAD

**Issue by marmelo** [marmelo/streaming-pt#8]

**Comment by pcaetanom** [comment]
rtsp://ewns-hls-b-stream.hexaglobe.net/rtpeuronewslive/pt_vidan750_rtp.sdp

**Comment by marado** [comment]
@pcaetanom Thanks, I've changed my Euronews pull request to your, more direct, stream link.

**Comment by pcaetanom** [comment]
No prob, I bumped into it reading through another project for a Kodi add-on 
[channels.py](https://github.com/k3oni/plugin.video.world.news.live/blob/master/channels.py).

But do double check that mplayer handles that link correctly, in my machine it stutters, but the same rtsp session works fine with mpv.

######################################################
######################################################
sdp file:
v=0
o=- 341213981 341213981 IN IP4 127.0.0.1
s=pt_vidan750_rtp.sdp
c=IN IP4 0.0.0.0
t=0 0
a=sdplang:en
a=range:npt=now-
a=control:*
m=audio 0 RTP/AVP 96
a=rtpmap:96 mpeg4-generic/48000/1
a=fmtp:96 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1188
a=control:trackID=1
m=video 0 RTP/AVP 97
a=rtpmap:97 H264/90000
a=fmtp:97 packetization-mode=1;profile-level-id=42C00D;sprop-parameter-sets=Z0LADdoGh+/8AKAAnEAAAAMAQAAADKPFCqg=,aM48gA==
a=cliprect:0,0,240,416
a=framesize:97 416-240
a=framerate:25.0
a=control:trackID=2

######################################################
######################################################
mplayer session :
==> Found audio stream: 0
======= WAVE Format =======
Format Tag: 20557 (0x504D)
Channels: 1
Samplerate: 48000
avg byte/sec: 0
Block align: 1
bits/sample: 0
cbSize: 2
Unknown extra header dump: [11] [88] 
==========================================================================
[lavf] stream 0: audio (aac), -aid 0
==> Found video stream: 1
======= VIDEO Format ======
  biSize 78
  biWidth 416
  biHeight 240
  biPlanes 0
  biBitCount 0
  biCompression 875967048='H264'
  biSizeImage 0
Unknown extra header dump: [0] [0] [0] [1] [67] [42] [c0] [d] [da] [6] [87] [ef] [fc] [0] [a0] [0] [9c] [40] [0] [0] [3] [0] [40] [0] [0] [c] [a3] [c5] [a] [a8] [0] [0] [0] [1] [68] [ce] [3c] [80] 
===========================
######################################################
######################################################
mpv session:

[libav/demuxer] rtsp: audio codec set to: aac
[libav/demuxer] rtsp: audio samplerate set to: 48000
[libav/demuxer] rtsp: audio channels set to: 1
[libav/demuxer] rtsp: video codec set to: h264
[libav/demuxer] rtsp: RTP Packetization Mode: 1
[libav/demuxer] rtsp: RTP Profile IDC: 42 Profile IOP: c0 Level: d
[libav/demuxer] rtsp: Extradata set to 0x7fd7891f21c0 (size: 38)!
[libav/demuxer] rtsp: hello state=0

######################################################
######################################################

Could be an issue with my setup (Jessie AMD64) but double check if it's the same for everyone.

**Comment by marado** [comment]
I tested it with mplayer on Jessie, x86, and saw no problems, but it was a
quick test... Anyhow, it is surely better than the scraping I was doing
previously.
